services:
  - type: web
    runtime: node
    name: esgi.render.nodejs
    region: frankfurt
    plan: free
    repo: https://github.com/Gautierrr/exerciceCloud
    branch: main
    buildCommand: npm install
    startCommand: npm run start
    envVars:
      - key:  DB_URL
        fromDatabase:
          name: exercicecloud
          property: connectionString

databases:
  - name: exercicecloud
    plan: free
    region: frankfurt